const productsTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCTS_START: "DELETE_PRODUCTS_START",
  FETCH_CURRENT_PRODUCT_START: "FETCH_CURRENT_PRODUCT_START",
  SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",

  GET_PRODUCT_DESC: "GET_PRODUCT_DESC",
  SET_PRODUCT_DESC: "SET_PRODUCT_DESC"
}

export default productsTypes;