const productsTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCTS_START: "DELETE_PRODUCTS_START",
  FETCH_CURRENT_PRODUCT_START: "FETCH_CURRENT_PRODUCT_START",
  SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",

  SET_RANDOM_PRODUCTS: "SET_RANDOM_PRODUCTS",

  FETCH_CONTENT_EDIT_MAIN_PRODUCT: "FETCH_CONTENT_EDIT_MAIN_PRODUCT",
  SET_EDIT_CONTENT_MAIN_PRODUCT: "SET_EDIT_CONTENT_MAIN_PRODUCT",
  UPDATE_CONTENT_MAIN_PRODUCT:"UPDATE_CONTENT_MAIN_PRODUCT",
  
  FETCH_RANDOMS_PRODUCTS: "FETCH_RANDOMS_PRODUCTS",

  LOADING_TOGGLE_ACTION_PRODUCTS:"LOADING_TOGGLE_ACTION_PRODUCTS",
  LOADING_TOGGLE_ACTION_CURRENT_PRODUCTS:"LOADING_TOGGLE_ACTION_CURRENT_PRODUCTS",
  SET_LOADED_PRODUCTS:"SET_LOADED_PRODUCTS"
}

export default productsTypes;