const commentsTypes = {
    SAVE_COMMENT_START:"SAVE_COMMENT_START",
    FETCH_COMMENT_START:"FETCH_COMMENT_START",
    SET_COMMENT_START:"SET_COMMENT_START",

    DELETE_COMMENT:"DELETE_COMMENT",

    // FETCH_NEWS_EDIT: "FETCH_NEWS_EDIT",
    // SET_EDIT_NEWS: "SET_EDIT_NEWS",
    // UPDATE_NEWS:"UPDATE_NEWS",
}

export default commentsTypes;