const userTypes ={
    EMAIL_SIGN_IN_START:"EMAIL_SIGN_IN_START",
    SIGN_IN_SUCCESS:"SIGN_IN_SUCCESS",
    CHECK_USER_SESSION:"CHECK_USER_SESSION",
    SIGN_OUT_USER_START:"SIGN_OUT_USER_START",
    SIGN_OUT_USER_SUCCESS:"SIGN_OUT_USER_SUCCESS",
    REGIST_USER_START:"REGIST_USER_START",
    REGIST_USER_SUCCESS:"REGIST_USER_SUCCESS",

    RESET_PASSWORD_START:"RESET_PASSWORD_START",
    RESET_PASSWORD_SUCCESS:"RESET_PASSWORD_SUCCESS",

    GET_ALL_USERS:"GET_ALL_USERS",
    SET_ALL_USERS:"SET_ALL_USERS",
    GIVE_USER_ROLES:"GIVE_USER_ROLE",
    DELETE_USER:"DELETE_USER",

    USER_ERROR:"USER_ERROR",
    GOOGLE_SIGN_IN_START:"GOOGLE_SIGN_IN_START",
    RESET_USER_STATE:"RESET_USER_STATE",

    RESET_AUTH_FORM:"RESET_AUTH_FORM",

    LOADING:"LOADING"
}

export default userTypes;