const homeTypes = {
    ADD_NEW_HOME_CONTENT: "ADD_NEW_HOME_CONTENT",
    FETCH_CONTENT_START: "FETCH_CONTENT_START",
    SET_CONTENT: "SET_CONTENT",
    DELETE_CONTENT_START: "DELETE_CONTENT_START",

   
    ADD_NEW_HOME_CONTENT_TESTIMONALS: "ADD_NEW_HOME_CONTENT_TESTIMONALS",
    FETCH_CONTENT_TESTIMONALS_START: "FETCH_CONTENT_TESTIMONALS_START",
    SET_CONTENT_TESTIMONALS: "SET_CONTENT_TESTIMONALS",
    DELETE_CONTENT_TESTIMONALS_START: "DELETE_CONTENT_TESTIMONALS_START",
    // FETCH_CURRENT_PRODUCT_START: "FETCH_CURRENT_PRODUCT_START",
    // SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",
    FETCH_CONTENT_EDIT: "FETCH_CONTENT_EDIT",
    SET_EDIT_CONTENT: "SET_EDIT_CONTENT",
    UPDATE_CONTENT:"UPDATE_CONTENT"
  }
  
  export default homeTypes;