const homeTypes = {
    ADD_NEW_HOME_CONTENT: "ADD_NEW_HOME_CONTENT",
    FETCH_CONTENT_START: "FETCH_CONTENT_START",
    SET_CONTENT: "SET_CONTENT",
    DELETE_CONTENT_START: "DELETE_CONTENT_START",

   
    ADD_NEW_HOME_CONTENT_TESTIMONALS: "ADD_NEW_HOME_CONTENT_TESTIMONALS",
    FETCH_CONTENT_TESTIMONALS_START: "FETCH_CONTENT_TESTIMONALS_START",
    SET_CONTENT_TESTIMONALS: "SET_CONTENT_TESTIMONALS",
    DELETE_CONTENT_TESTIMONALS_START: "DELETE_CONTENT_TESTIMONALS_START",

    FETCH_CONTENT_EDIT: "FETCH_CONTENT_EDIT",
    SET_EDIT_CONTENT: "SET_EDIT_CONTENT",
    UPDATE_CONTENT:"UPDATE_CONTENT",

    FETCH_CONTENT_EDIT_PRODUCT: "FETCH_CONTENT_EDIT_PRODUCT",
    UPDATE_CONTENT_PRODUCT:"UPDATE_CONTENT_PRODUCT",


    ADD_NEW_HOME_CONTENT_INSTAGRAM: "ADD_NEW_HOME_CONTENT_INSTAGRAM",
    FETCH_CONTENT_START_INSTAGRAM: "FETCH_CONTENT_START_INSTAGRAM",
    SET_CONTENT_INSTAGRAM: "SET_CONTENT_INSTAGRAM",
    DELETE_CONTENT_INSTAGRAM_START: "DELETE_CONTENT_INSTAGRAM_START",

    FETCH_CONTENT_EDIT_INSTAGRAM: "FETCH_CONTENT_EDIT_INSTAGRAM",
    UPDATE_CONTENT_INSTAGRAM:"UPDATE_CONTENT_INSTAGRAM",

    LOADING_TOGGLE_ACTION:"LOADING_TOGGLE_ACTION",

    FETCH_CONTENT_SERIES: "FETCH_CONTENT_SERIES",
    SET_CONTENT_SERIES: "SET_CONTENT_SERIES",
  }
  
  export default homeTypes;