const newsTypes = {
    SAVE_NEWS_START:"SAVE_NEWS_START",
    GET_NEWS_START:"GET_NEWS_START",
    SET_NEWS_START:"SET_NEWS_START",
    FETCH_NEWS_DETAILS_START:"GET_NEWS_DETAILS_START",
    SET_NEWS_DETAILS:"SET_NEWS_DETAILS",

    FETCH_NEWS_HISTORY:"FETCH_NEWS_HISTORY",
    DELETE_NEWS:"DELETE_NEWS",

    FETCH_NEWS_EDIT: "FETCH_NEWS_EDIT",
    SET_EDIT_NEWS: "SET_EDIT_NEWS",
    UPDATE_NEWS:"UPDATE_NEWS",
}

export default newsTypes;