const ordersTypes = {
    SAVE_ORDER_HISTORY_START:"SAVE_ORDER_HISTORY_START",
    GET_USER_ORDER_HISTORY:"GET_USER_ORDER_HISTORY",
    SET_USER_ORDER_HISTORY:"SET_USER_ORDER_HISTORY",
    GET_ORDER_DETAILS_START:"GET_ORDER_DETAILS_START",
    SET_ORDER_DETAILS:"SET_ORDER_DETAILS",

    FETCH_ORDERS_HISTORY:"FETCH_ORDERS_HISTORY",
    DELETE_ORDER:"DELETE_ORDER",
    SET_ACTIVITY:"SET_ACTIVITY",
    SET_LOADED_ORDERS:"SET_LOADED_ORDERS"
}

export default ordersTypes;